### ISSUE TITLE
ffmpeg compiled with NDI support

### ISSUE THREAD

**Issue by magdesign** [belthesar/ndi-rtmp-encoder#4]
Could you please add a link or a description on how to compile ffmpeg with NDI support.
Installed the newest ffmpeg 3.4.4 but NDI is not supported by default.

Would be amazing :-)

**Comment by belthesar** [comment]
Hi! So, a couple things - Until Newtek changes the license terms of the NDI libraries, I don't believe I'll be able to distribute my own compiled ffmpeg binaries with the NDI license.  With that said, I'm woefully overdue for providing compilation instructions, so I'll see about getting those updated soon. Thanks for your interest!

**Comment by magdesign** [comment]
Cool, looking forward to it :-)
I searched the internet for several hours but could not find a useful guide on how to include the NDI libraries nor a compiled version with them included.

**Comment by magdesign** [comment]
Solved using this guide: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

adding this flags:  

 --enable-libndi_newtek 
  --extra-cflags="-I/home/youruser/ffmpeg_build/ndi/include" 
  --extra-ldflags="-L/home/youruser/ffmpeg_build/ndi/include"

and copying all ndi sdk content to: /home/youruser/ffmpeg_build/ndi/

thanks.
