### ISSUE TITLE
Ffmpeg+ndi+rtmp compilation instructions

### ISSUE THREAD

**Issue by sneakyjoeru** [belthesar/ndi-rtmp-encoder#5]
Is it possible to get such instructions for the humanity?

**Comment by belthesar** [comment]
Instructions were provided with the most recent commit.

**Comment by sneakyjoeru** [comment]
I can't seem to find 4.1.5 version of ffmpeg at https://github.com/FFmpeg/FFmpeg/releases
Can you please point at proper version that will work?

**Comment by belthesar** [comment]
(At the time of this comment) Try page 2.

**Comment by sneakyjoeru** [comment]
Whoops. I wonder how I missed it. Thanks. 
https://github.com/FFmpeg/FFmpeg/releases/tag/n4.1.5
